version: '3'

services:
  postgres:
    container_name: postgres-scam
    image: postgres
    environment:
      POSTGRES_DB: "scam_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5435:5432"

  postgres-test:
    container_name: postgres-scam-test
    image: postgres
    environment:
      POSTGRES_DB: "scam_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/postgres
    volumes:
      - postgres-test:/data/postgres
    ports:
      - "5436:5432"
volumes:
    postgres:
    postgres-test: